# 7.DataBase



> DB(DataBase): 구조화된 정보 또는 데이터의 조직화된 모음  
DBMS(DataBase Management System): 사용자와 데이터베이스 사이에서 사용자의 요구에 따라 정보를 생성해 주고 데이터베이스를 관리해 주는 소프트웨어  
RDBMS(Relational DataBase Management System): 테이블과 다른 테이블이 관계를 맺고 모여있는 집합체  
SQL(Structured Query Language): 관계형 데이터베이스에서 사용되는 언어로 데이터를 쿼리, 조작 및 정의하고 액세스 제어를 제공

## 7.1 PostgreSQL

오픈소스 RMDBS의 한 종류

## 7.2 기본 커맨드
접속
```
psql -U postgres
```
<br>

종료
```
\q
```
<br>

DB 조회
```
\l or \list  
```
<br>

유저 조회
```
\du
```  
<br>

테이블 조회
```
\dt(+)
```
<br>

테이블 정보 조회
```
\d *table_name*
```  
<br>

테이블 접근
 ```
 \c *table_name*
 ```

## 7.3 테이블 커맨드

생성
```
CREATE TABLE *table_name*  
(  
  id SERIAL PRIMARY KEY,  
  press_name VARCHAR(10) UNIQUE NOT NULL  
);
```
<br>

삭제
```
DROP TABLE *table_name*;
```
<br>

컬럼 추가
```
ALTER TABLE *table_name* ADD COLUMN *column* varchar(10);
```
<br>

컬럼 삭제
```
ALTER TABLE *table_name* DROP COLUMN *column*;
```
<br>

컬럼 이름 변경
```
ALTER TABLE *table_name* RENAME COLUMN *current_column* TO *new_column*;
```
<br>

컬럼 타입 변경
```
ALTER TABLE *table_name* ALTER COLUMN *column* TYPE *data_type*;
```

## 7.4 CRUD

Create<br>
테이블 전체 컬럼 순서대로 데이터 입력
```
INSERT INTO *table_name* 
VALUES (
  *value1*,
  *value2*,
  ...
)
```
<br>

테이블 특정 컬럼 데이터 입력
```
INSERT INTO *table_name*
(
  *column1*,
  *column2*
)
VALUES
(
  *value1*,
  *value2*
);
```
<br>

Read
```
SELECT * FROM *table_name* # 모든 컬럼 조회
SELECT *column_name1, column_name2, ...* FROM *table_name* # 특정 컬럼 조회
```
<br>

Update<br>
일반적으로는 where절과 같이 사용
```
UPDATE *table_name* SET *column_name* = *value*
```
<br>

Delete<br>
일반적으로는 where절과 같이 사용
```
DROP FROM *table_name* # 전체 테이블 내용 삭제
```
<br>

## 7.5 EDA

### 새로운 컬럼 만들기

```
SELECT DISTINCT *column*, (*column2* + *column3*)/2 as avg
FROM *table_name*;
```

### 중복 제거
```
SELECT DISTINCT *column*
FROM *table_name*;
```

### 조건식

#### WHERE
단순 조건식
```
SELECT * 
FROM
  *table_name* 
WHERE 
  column != -1;
```
<br>

여러 조건식
```
SELECT * 
FROM 
  *table_name* 
WHERE 
  *column1* != -1 and *column2* >= 10 or *column3* < 100;
```
<br>

조건식 범위 지정 방법
```
WHERE 
  *column* BETWEEN 0 AND 10;
WHERE 
  *column* NOT BETWEEN 0 AND 10;

WHERE 
  *column* IN (0, 1, 10);
WHERE 
  *column* NOT IN (0, 1, 10);
```
<br>

문자열 검색
_: 몇 글자인지 정해줌 <br>
%: 몇 글자인지 정해주지 않음 <br>
```
WHERE 
  *column* LIKE *pattern*;
WHERE 
  *column* NOT LIKE *pattern;
```
<br>

패턴의 종류는 아래와 같음

```
LIKE '200%': 200으로 시작하는 값
LIKE '%200': 200으로 끝나는 값
LIKE '%200%': 200이 포함되는 값
LIKE '_0_': 가운데가 0이 들어가는 3자리 값
LIKE '_1': x1로 끝나는 값
LIKE '_200%': 200 앞에는 어떠한 문자도 상관 없으며 200이 포함된 문자열

```

#### CASE WHEN
조건에 따라 다른 값을 보여줄 때 사용
```
CASE 
  WHEN 
    condition_1 THEN result_1
  WHEN 
    condition_2 THEN result_2
  ...
  END AS *new_column name*

```

### 집계함수

count: row의 개수 반환
```
SELECT count(*) FROM *table_name*;
```
<br>

sum: 합계 반환
```
SELECT sum(*column*) FROM *table_name*;
```
<br>

avg: 평균 반환
```
SELECT avg(*column*) FROM *table_name*;
```
<br>

max: 최댓값 반환
```
SELECT max(*column*) FROM *table_name*;
```
<br>

min: 최솟값 반환
```
SELECT min(*column*) FROM *table_name*;
```

<br>
<br>
<br>

주의: 집계함수는 where 절에 나올 수 없음
```
SELECT id FROM news WHERE news_count = max(news_count);
```
<br>

위의 쿼리는 아래와 같이 수정해야 함
```
SELECT id FROM news
WHERE news_count = (SELECT max(news_count) FROM news);
```

### 정렬

컬럼을 기준으로 오름차순 혹은 내림차순으로 정렬

오름차순
```
SELECT 
  *column*
FROM 
  *table_name*
ORDER BY 
  *column*;
```
<br>

내림차순
```
SELECT 
  *column*
FROM 
  *table_name*
ORDER BY 
  *column* DESC;
```
<br>
<br>

GROUP BY 뒤에는 집계 함수도 들어갈 수 있음
```
SELECT 
  *column*
FROM 
  *table_name*
ORDER BY 
  sum(*column*) DESC;
```

### GROUP BY
행을 특정 그룹으로 묶음

```
SELECT 
  *column*
FROM 
  *table_name*
GROUP BY
	*column*;
```

### RANK

RANK: 전체 순위를 집계
```
SELECT id, press_name, news_count,
       RANK() OVER (PARTITION BY press_name ORDER BY news_count DESC)
FROM news;
```
<br>

DENSE_RANK: 집합 내 순위를 집계 <br>
중복 발생 시 다음 순위를 생략하지 않음 <br>
(1, 1, 2)
```
SELECT id, press_name, news_count,
       DENSE_RANK() OVER (PARTITION BY press_name ORDER BY news_count DESC)
FROM news;
```

### JOIN

(INNER)JOIN<br>
같은 값이 있는 행만 반환
```
SELECT *column1*, *column2*
FROM press_ids as p
JOIN news as n
ON *p.column1* = *n.column1*';
```

LEFT JOIN<br>
왼쪽 테이블에 오른쪽 테이블을 매칭, 값이 없으면 NULL 삽입
```
SELECT *column1*, *column2*
FROM press_ids as p
LEFT JOIN news as n
ON *p.column1* = *n.column1*';
```
<br>

RIGHT JOIN<br>
오른쪽 테이블에 오른쪽 테이블을 매칭, 값이 없으면 NULL 삽입
```
SELECT *column1*, *column2*
FROM press_ids as p
RIGHT JOIN news as n
ON *p.column1* = *n.column1*';
```
<br>

FULL JOIN
오른쪽 테이블과 왼쪽 테이블 매칭
```
SELECT *column1*, *column2*
FROM press_ids as p
RIGHT JOIN news as n
ON *p.column1* = *n.column1*';
```
<br>

CROSS JOIN: Table1과 Table2의 모든 행을 JOIN (별도의 키를 지정하지 않음)
```
SELECT *column1*, *column2*
FROM press_ids as p
CROSS JOIN news as n;
```

## 7.6 Database Link in Python

In [83]:
import psycopg2 as pg2
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
from sqlalchemy import create_engine

In [75]:
conn = pg2.connect(
    host = 'localhost',
    dbname = 'postgres',
    user = 'postgres',
    password = 'postgrespw',
    port = 49153
)

cur = conn.cursor()

In [9]:
# 이건 구시대 사용안함, 판다스 사용
cur.execute('select * from news_id')
cur.fetchall()

[('015', '조선일보'), ('023', '동아일보')]

파이썬에서 DB로 데이터 올리기

In [48]:
oid = '047'
press_name = '서울일보'

cur.execute(f"INSERT INTO news_id values ('{oid}','{press_name}');")
conn.commit()

In [76]:
pd.read_sql('select * from news_id', conn)

c:\Users\user\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

    oid press_name
0   081       서울신문
1   022       세계일보
2   025       중앙일보
3   028        한겨레
4   469       한국일보
5   032       경향신문
6   005       국민일보
7   020       동아일보
8   021       문화일보
9   015       힌국경제
10  023       조선일보

In [62]:
def bs_object_from_url(url):
    response = requests.get(url, headers={'User-Agent': 'Mozilla 5.0'})
    bs = BeautifulSoup(response.text, 'lxml')

    return bs

def get_contents_from_rul(url):
    bs = bs_object_from_url(url)

    if bs.select('#contents'):
        return bs_object_from_url(url).select('#contents')[0].text.strip()

    if bs.select('.content'):
        return bs_object_from_url(url).select('.content')[0].text.strip()

    return -1

def crawl_news(date, oid, page):
    url = f'https://news.naver.com/main/list.naver?mode=LPOD&mid=sec&oid={oid}&date={date}&page={page}'
    bs_page = bs_object_from_url(url)

    title_and_content_links = bs_page.select('dt > a')[1::2]
    titles =  [title_and_content_link.text.strip() for title_and_content_link in title_and_content_links]
    content_urls = [title_and_content_link.get('href') for title_and_content_link in title_and_content_links]
    contents = [get_contents_from_rul(url) for url in content_urls]

    temp = pd.DataFrame({
        'date': date,
        'oid': oid,
        'title': titles,
        'content': contents,
        'content_url': content_urls
    })

    return temp

In [94]:
news_data = crawl_news('20221210','022',1)

In [95]:
news_data

,date,oid,title,content,content_url
0,20221210,022,‘최측근’ 정진상 기소에… 이재명 “법정서 무고함 밝혀질 것”,2억4000만원 뇌물 수수 등 혐의 구속 이후 수수액 1억원 더 늘어 검찰이 더불어...,https://n.news.naver.com/mnews/article/022/000...
1,20221210,022,법·원칙 앞에 화물연대 총파업 철회… 안전운임제도 일몰 위기,운송 거부 15일 만에 종료조합원 투표 61.8%가 ‘찬성’ 논란의 안전운임제 연장...,https://n.news.naver.com/mnews/article/022/000...
2,20221210,022,野 단독 삭감 예산 수정안 제시… 국회의장 “與野 합의 필요” 거부,정기국회 마지막 날까지 대립 예정된 본회의도 못 열고 끝나정기국회 마지막 날인 9일...,https://n.news.naver.com/mnews/article/022/000...
3,20221210,022,"현재·미래, 생물·무생물의 모호한 경계…그 속에서 발견한 미학 [김한들의 그림 아로...","(98) 우리가 빛의 속도로 갈 수 있다면양혜규, 시간·문화 등 개념 다원적 접근시...",https://n.news.naver.com/mnews/article/022/000...
4,20221210,022,괴짜 천재에서 괴짜 옷 입은 악마로… 뱅크먼프리드의 몰락 [세계는 지금],보통의 20대 모습… 새 유형 갑부로 각광효율적 이타주의 언급하며 기부 적극FTX ...,https://n.news.naver.com/mnews/article/022/000...
5,20221210,022,투자자 신뢰 상실한 ‘코인’… 금융시장 진출 구상도 ‘빨간불’ [세계는 지금],가상화폐 거래소 FTX 파산 한 달FTX사태로 업계 지급능력 문제 대두가상화폐 거래...,https://n.news.naver.com/mnews/article/022/000...
6,20221210,022,11일 이상민 해임건의안 본회의 표결… 예산안은 15일로 합의,국회는 11일 오전 10시 본회의를 열어 더불어민주당이 발의한 이상민 행정안전부 장...,https://n.news.naver.com/mnews/article/022/000...
7,20221210,022,국내 주요기업 ‘스타트업 지원’ 팔 걷었다 [심층기획],"삼성전자 사내 벤처 육성 프로그램 이어외부 스타트업 선발해 최대 1억원 지급현대차,...",https://n.news.naver.com/mnews/article/022/000...
8,20221210,022,‘이태원 참사 유가족협의회’ 출범… 이상민 파면 요구 [이태원 핼러윈 참사],이태원 참사 희생자 유가족 협의체가 10일 공식 발족했다. 10·29 이태원...,https://n.news.naver.com/mnews/article/022/000...
9,20221210,022,불황에 움츠린 기업들… 인플레에 투자비 늘고 수요 줄어 [심층기획],대내외 악재 겹쳐 ‘비상 경영’글로벌 경기 침체 속 원자재 가격 상승고환율·고금리 ...,https://n.news.naver.com/mnews/article/022/000...
10,20221210,022,[속보] 11일 국회 본회의서 이상민 해임 건의안 표결·내년 예산안은 15일 처리,이상민 행정안전부 장관이 지난 9일 정부 서울 청사 별관에서 열린 ‘제12회 지방자...,https://n.news.naver.com/mnews/article/022/000...
11,20221210,022,이신화 “일본인 납북 피해자 가족 고통·분노 전적으로 공유”,이신화 북한인권국제협력대사. 뉴스1 이신화 북한인권국제협력대사(북한인권대사)는...,https://n.news.naver.com/mnews/article/022/000...
12,20221210,022,제주에 ‘BTS길’이 있었네… “누군가 잘 알고 싶다면 함께 걸어라” [줌인(人)],올해로 15주년 맞은 제주올레길 닦은 안은주 대표길 통해 지역·사람 연결하고 관계 ...,https://n.news.naver.com/mnews/article/022/000...
13,20221210,022,"中, 방역 완화 후 신규확진자 급감… 통계 불신 확산",중국 당국이 방역을 완화한 뒤 중국의 코로나19 신규 감염자가 급감한 것으로 발표되...,https://n.news.naver.com/mnews/article/022/000...
14,20221210,022,“고맙고 고맙다. 다음 생 있다면 꼭 다시 만나자”… 文 반려견 ‘마루’ 세상 떠났다,"문재인 전 대통령, 직접 페이스북 통해 전해 \n\n\n\n 문재인 전 대통령과...",https://n.news.naver.com/mnews/article/022/000...
15,20221210,022,“남자→여자로 성전환…인기 얻자 ‘사칭 빌런’ 꼬이기도” 풍자의 고백,-1,https://n.news.naver.com/mnews/article/022/000...
16,20221210,022,"中 방역전문가 ”중의학, 양방보다 코로나19 치료에 효과적”","“일반 감염자·경증자, 중의학 치료…중환자, 중방·양방치료 병행 해야”“발열·인후통...",https://n.news.naver.com/mnews/article/022/000...
17,20221210,022,"둘째 임신 중 8시간 대청소? 최희, ‘한강뷰’ 집 얼마나 넓길래?",-1,https://n.news.naver.com/mnews/article/022/000...
18,20221210,022,野 “예산안 협상 타결 관계없이 11일 이상민 해임건의안 처리”,더불어민주당 박홍근 원내대표가 지난 9일 국회 원내대표실에서 여야 예산안 협상 과정...,https://n.news.naver.com/mnews/article/022/000...
19,20221210,022,"1857년 침몰 난파선서 찾은 청바지, 1억5000만원에 팔렸다",美서 열린 경매에 나온 19세기 ‘골드러시’ 관련 유물 270점 중 하나‘세계 최초...,https://n.news.naver.com/mnews/article/022/000...
20,20221210,022,"“둘이 성관계 해봐” 가출 청소년 돌본다며 성희롱·강제추행 혐의 교사, 항소심도 ‘유죄’",가출 청소년을 보호한다던 교사가 이들에게 성관계를 해보라고 시키는 등 성희롱과 강제...,https://n.news.naver.com/mnews/article/022/000...
21,20221210,022,직장인은 힙한 어촌 근무… 주민들은 힘찬 손님맞이 [S 스토리],‘워케이션’ 지역회생 대안 부상직장인 ‘꿈의 근무환경’ 中企로 확산직원들 기 살리고...,https://n.news.naver.com/mnews/article/022/000...
22,20221210,022,카타르 커피가 ‘Dreamers’인 이유 [박영순의 커피 언어],한 잔의 커피를 마실 때 향과 맛을 구체적인 속성으로 비유하는 것은 어떤 의미가 있...,https://n.news.naver.com/mnews/article/022/000...

In [68]:
news_data.columns

Index(['date', 'oid', 'title', 'content', 'content_url'], dtype='object')

In [80]:
for row in tqdm(news_data.itertuples()) :
    title = row.title.replace('\'','\"')
    content = row.content.replace('\'','\"')
    # query = f"INSERT INTO naver_news values ('{row.date}','{row.oid}','{title}','{content}','{row.content_url}');"

    cur.execute(f"INSERT INTO naver_news values ('{row.date}','{row.oid}','{title}','{content}','{row.content_url}');")
    conn.commit()

22it [00:00, 34.42it/s]

In [82]:
pd.read_sql('select * from naver_news;',conn)

c:\Users\user\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,date,oid,title,content,content_url
0,20221210,015,"5년간 멈췄던 ""한빛 4호기"" 재가동","원안위 ""원전 안전성 확인""\n\n\n\n원자력안전위원회가 안전 점검 명목으로 5년...",https://n.news.naver.com/mnews/article/015/000...
1,20221210,015,"부결 하루 만에…""한전채 확대법"" 재추진하는 국회","전기료 인상 등 ""전력대란"" 우려에 여야, 부랴부랴 본회의 상정 속도여야가 9일 한...",https://n.news.naver.com/mnews/article/015/000...
2,20221210,015,"이태원 참사 유가족협의회 출범…권성동 ""세월호"" 언급 논란","사진=연합뉴스이태원 참사 희생자 유가족이 만든 협의체가 10일 공식 발족한 가운데,...",https://n.news.naver.com/mnews/article/015/000...
3,20221210,015,"오열하던 네이마르 위로한 소년, 정체 알고 보니 ""반전""",사진=AFP2022 카타르 월드컵 8강전에서 패배한 후 눈물을 쏟은 네이마르를 위로...,https://n.news.naver.com/mnews/article/015/000...
4,20221210,015,"1045회 로또 1등 ""6, 14, 15, 19, 21, 41""…당첨자 13명 19억씩","10일 제1045회 로또복권 추첨 결과 ""6, 14, 15, 19, 21, 41""이...",https://n.news.naver.com/mnews/article/015/000...
5,20221210,015,"""이러다 카뱅 꼴 나는 거 아냐?""…LG엔솔 직원들 ""멘붕"" [박의명의 불개미 구조대]",사진=뉴스1대박의 꿈을 품고 우리사주에 투자했던 LG에너지솔루션 직원들이 멘붕에 걸...,https://n.news.naver.com/mnews/article/015/000...
6,20221210,015,"브라질 월드컵 탈락에 소환된 ""고양이의 저주""…왜?",사진=AFP2022 카타르 월드컵의 강력한 우승 후보였던 브라질의 탈락을 두고 해외...,https://n.news.naver.com/mnews/article/015/000...
7,20221210,015,"이런 몸으로 헤딩까지…""손흥민 월드컵 출전은 도박이었다""",사진=연합뉴스손흥민이 몸 상태가 예상보다 훨씬 좋지 않다는 영국 의학전문가의 의견이...,https://n.news.naver.com/mnews/article/015/000...
8,20221210,015,[속보] 이상민 해임안 내일 본회의 표결…예산안은 15일 합의처리,이상민 행정안전부 장관/사진=연합뉴스국회는 오는 11일 오전 본회의를 열어 더불어민...,https://n.news.naver.com/mnews/article/015/000...
9,20221210,015,"""캡틴 조로""부터 ""한반두""까지…월드컵에 들썩인 한국 [이슈+]",2022 카타르 월드컵국내 화제의 순간 모음\n\n\n\n12년 만의 월드컵 16강...,https://n.news.naver.com/mnews/article/015/000...
10,20221210,015,"文 ""마루가 저세상으로 떠났다""…반려견 사망 소식 알려","""아침 산책 중 스르르 주저 앉아""""더없이 고마운 친구""…애정 드러내\n\n\n\n...",https://n.news.naver.com/mnews/article/015/000...
11,20221210,015,"머스크, 거액 들여 트위터 사더니…""세계 최고 부자"" 자리 위태","일론 머스크 /사진=로이터연합뉴스일론 머스크 테슬라 최고경영자(CEO)가 ""세계 최...",https://n.news.naver.com/mnews/article/015/000...
12,20221210,015,"달리던 덤프트럭, 펜션 들이받고 호수로 추락…운전자 사망",사진=게티이미지뱅크전라북도 진안에서 도로를 달리던 25t 덤프트럭이 호수로 추락해 ...,https://n.news.naver.com/mnews/article/015/000...
13,20221210,015,"월드컵 16강 오르자 ""반전""…지켜보던 ""그들""이 움직였다 [신현보의 딥데이터]","尹 지지율 33%…3개월만 최고치與, 오차범위 밖 野 역전…3개월만중도층 파업+월드...",https://n.news.naver.com/mnews/article/015/000...
14,20221210,015,"""도로의 의인들""…의식 잃은 운전자 구조한 육군 부사관들",도로 위에서 의식 잃은 운전자를 구조한 육군 28사단 예하 광명대대의 한정휘 중사(...,https://n.news.naver.com/mnews/article/015/000...
15,20221210,015,부모가 시골집에 김장하러 간 사이…혼자 자던 6살 딸 참변,사진은 기사와 무관/사진=게티이미지뱅크부모가 김장하러 간 사이 공장에서 난 불로 이...,https://n.news.naver.com/mnews/article/015/000...
16,20221210,015,"머스크, ""팝의 전설"" 엘턴 존에 ""돌아와 달라"" 사정한 이유","엘턴 존 /사진=AP""팝의 전설"" 엘턴 존(75)이 트위터 탈퇴를 선언했다. 110...",https://n.news.naver.com/mnews/article/015/000...
17,20221210,015,"""한국인들 1~2살씩 어려진다""…외신도 덩달아 ""떠들썩""","가수 싸이 /사진=한경DB내년 6월부터 사법, 행정 분야에서 ""만 나이""가 사용되는...",https://n.news.naver.com/mnews/article/015/000...
18,20221210,015,"""반려동물 달력"" 만든 文에…與 ""풍산개는 버리면서 모순""",문재인 전 대통령과 반려동물들의 삽화가 담긴 달력 이미지 /사진=텀블벅 캡처국민의힘...,https://n.news.naver.com/mnews/article/015/000...
19,20221210,015,"콧대 높은 아이폰 ""10년 고집"" 꺾이나…관심 쏟아지는 이유 [배성수의 다다IT선]",사진=맥루머스애플이 이르면 내년부터 아이폰에도 USB-C타입 충전기를 수용할 것으로...,https://n.news.naver.com/mnews/article/015/000...
20,20221210,015,"이재명 ""한 점 부끄러움 없다""…與 ""기출문제 예상 답변""",이재명 더불어민주당 대표 /사진=연합뉴스이재명 더불어민주당 대표가 최측근인 정진상 ...,https://n.news.naver.com/mnews/article/015/000...
21,20221210,015,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/015/000...

In [87]:
USERNAME = 'postgres'
PASSWORD = 'postgrespw'
DB_HOST = 'localhost'
PORT = 49153
DB_NAME = 'postgres'

db_url = f'postgresql://{USERNAME}:{PASSWORD}@{DB_HOST}:{PORT}/{DB_NAME}'
engine = create_engine(db_url, echo=True)

In [88]:
news_data = crawl_news('20221210','023',1)

In [89]:
news_data.to_sql(
  'naver_news',
  engine,
  if_exists='append', # replace: 덮어쓰기
  index=False
)

2022-12-11 11:06:07,973 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-12-11 11:06:07,974 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-12-11 11:06:07,978 INFO sqlalchemy.engine.Engine select current_schema()
2022-12-11 11:06:07,978 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-12-11 11:06:07,981 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-12-11 11:06:07,982 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-12-11 11:06:07,986 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2022-12-11 11:06:07,986 INFO sqlalchemy.engine.Engine [generated in 0.00060s] {'name': 'naver_news'}
2022-12-11 11:06:07,989 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-12-11 11:06:07,991 INFO sqlalchemy.engine.Engine INSERT INTO naver_news (date, oid, title, content, content_url) VALUES (%(date)s, %(oid)s, %(title)s, %(content)s, %(content_url)s)
2022-12-11 11:06:07,991 INFO sqlalchemy.engine.Engine [generated in 0.00072s] ({'date': '20221210', 'oid': '023', 'title': '원칙이 이겼다, 화물연대 16일만에 백기', 'content': '62% 찬성으로 파업 철회, 부산본부는 아예 투표없이 복귀대통령실 “천문학적 피해… 안전운임제도 개선 계기돼야”\n\n\n\n누구를 위한 파업이었나 - 9일 오후 경기 의왕시 내륙컨테이너기지 앞에서 민주노총 화물연대 소속의 한 조합원이 화물차에 걸려 있던 총파업 관련 ... (2904 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733823'}, {'date': '20221210', 'oid': '023', 'title': 'MB, 28일 0시 사면 유력… 김경수는 ‘복권없이 사면’ 검토', 'content': '28일 형 집행정지 종료일 맞춰 최경환·이병기·전병헌도 검토\t\t\t\t\t\t\t대통령실과 법무부가 일부 정치인과 경제인에 대한 사면·복권을 검토하고 있다. 이명박 전 대통령과 최경환 전 경제부총리는 사면·복권이 유력 검토되고 있고 이병기씨 등 전직 국정원장들도  ... (1939 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733751'}, {'date': '20221210', 'oid': '023', 'title': '실처럼 살짝 붙은 뼈… 英전문가 “손흥민의 월드컵은 도박이었다”', 'content': '손흥민이 2022 카타르 월드컵 조별리그 H조 3차전인 포르투갈과의 경기에서 마스크를 고쳐쓰고 있다. /뉴시스 “손흥민의 월드컵 출전은 도박이었다.”손흥민(30·토트넘)이 한국의 16강 진출 꿈을 이끌며 무사히 월드컵 여정을 마쳤지만, 한편에서는 그의 몸 상태에 대한 ... (2843 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733895'}, {'date': '20221210', 'oid': '023', 'title': '“콘서트 끝나고 성폭행” 폭로 나온 美유명가수… “거짓말” 반박', 'content': '미국 보이그룹 백스트리트보이즈의 멤버 닉 카터./ 로이터 뉴스1 \t\t\t\t\t\t\t\t\t\t미국 유명 보이그룹 백스트리트보이즈 멤버 닉 카터(42)가 20여년 전 장애인 여성 팬을 성폭행했다는 의혹을 전면 부인했다.9일(현지시각) CNN에 따르면 닉 카터 측 ... (2412 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733894'}, {'date': '20221210', 'oid': '023', 'title': '“원래 44살인데…” CNN이 韓 ‘만 나이’ 보도에 예로든 인물', 'content': '가수 싸이의 \'강남스타일\' 뮤직비디오 속 한 장면. /유튜브\t\t\t\t\t\t\t\t\t\t‘만 나이’ 사용을 규정한 민법·행정기본법 개정안이 최근 국회를 통과한 가운데, CNN이 이를 조명하며 “한국인들이 어려지게 됐다”고 보도했다. 특히 한국식 나이를 설명 ... (2044 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733893'}, {'date': '20221210', 'oid': '023', 'title': '화물연대 파업 철회 하루만에… 민노총 “안전운임제 사수” 집회', 'content': '민주노총 공공운수노조가 10일 오후 서울 영등포구 여의도에서 결의대회를 갖고 안전운임제 일몰제 3년 연장안에 대한 국회의 조속한 처리를 촉구하고 있다. /뉴스1\t\t\t\t\t\t\t\t\t\t민주노총이 화물연대의 총파업을 철회한 지 하루 만에 집회를 열고 안전운임 ... (1676 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733891'}, {'date': '20221210', 'oid': '023', 'title': '조화순 연세대 교수, 한국정치학회 제53대 회장 선출', 'content': '조화순 연세대 정치외교학과 교수 /한국정치학회\t\t\t\t\t\t\t\t\t\t조화순 연세대 정치외교학과 교수가 10일 제53대 한국정치학회장으로 선출됐다. 임기는 1년으로, 2024년 1월부터 시작된다.조 교수는 “미래를 위한 담론과 제도 변화에 기여하도록 새롭게 ... (1640 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733890'}, {'date': '20221210', 'oid': '023', 'title': '“뭘 봐 멍청아”… 분노한 메시, 승리 후에도 상대팀 도발, 왜?', 'content': '10일(한국시각) 2022 카타르월드컵 8강전 네덜란드전에서 득점한 리오넬 메시가 세리머니를 하고 있다./ 로이터 연합뉴스\t\t\t\t\t\t\t\t\t\t과열된 경기 탓이었을까. 아르헨티나 간판 스타 리오넬 메시가 네덜란드와의 월드컵 8강전에서 승리한 뒤에도 흥분 ... (2253 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733889'}  ... displaying 10 of 21 total bound parameter sets ...  {'date': '20221210', 'oid': '023', 'title': '', 'content': '金 “후원 모금 마감”… 모금 한도액 1억5000만원  金, 작년엔 국회의원 평균 못미치는 9900만원 모금  더탐사는 주거침입 범죄, 수사 상황 실시간 중계해 모금\n\n\n\n김의겸 더불어민주당 의원. /뉴스1\t\t\t\t\t\t\t\t\t\t유튜브 매체 더탐사 ... (3458 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733876'}, {'date': '20221210', 'oid': '023', 'title': '', 'content': '[박기자 쇄담]   영원한 우승 후보지만   번번히 8강 벽에 막혀   2014년엔 ‘미네이랑의 비극’  [쇄담(瑣談) : 자질구레한 이야기]이번 카타르 월드컵 우승 후보 1순위로 꼽혔던 브라질(FIFA랭킹 1위)이 꺾였다. 브라질은 10일 카타르 알라이얀의 에듀케이 ... (3848 characters truncated) ... 천합니다 버튼을 눌러주세요.  집계 기간 동안 추천을 많이 받은 기사는 네이버 자동 기사배열 영역에 추천 요소로 활용됩니다.\n\n레이어 닫기\n\n\n \n\n\n조선일보 언론사홈 바로가기\n\n\n \n\n언론사 구독 후 기사보기\n\n\n\n구독 없이 계속 보기', 'content_url': 'https://n.news.naver.com/mnews/article/023/0003733873'})
2022-12-11 11:06:07,996 INFO sqlalchemy.engine.Engine COMMIT

21

In [96]:
pd.read_sql('select * from naver_news;',conn)

c:\Users\user\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,date,oid,title,content,content_url
0,20221210,015,"5년간 멈췄던 ""한빛 4호기"" 재가동","원안위 ""원전 안전성 확인""\n\n\n\n원자력안전위원회가 안전 점검 명목으로 5년...",https://n.news.naver.com/mnews/article/015/000...
1,20221210,015,"부결 하루 만에…""한전채 확대법"" 재추진하는 국회","전기료 인상 등 ""전력대란"" 우려에 여야, 부랴부랴 본회의 상정 속도여야가 9일 한...",https://n.news.naver.com/mnews/article/015/000...
2,20221210,015,"이태원 참사 유가족협의회 출범…권성동 ""세월호"" 언급 논란","사진=연합뉴스이태원 참사 희생자 유가족이 만든 협의체가 10일 공식 발족한 가운데,...",https://n.news.naver.com/mnews/article/015/000...
3,20221210,015,"오열하던 네이마르 위로한 소년, 정체 알고 보니 ""반전""",사진=AFP2022 카타르 월드컵 8강전에서 패배한 후 눈물을 쏟은 네이마르를 위로...,https://n.news.naver.com/mnews/article/015/000...
4,20221210,015,"1045회 로또 1등 ""6, 14, 15, 19, 21, 41""…당첨자 13명 19억씩","10일 제1045회 로또복권 추첨 결과 ""6, 14, 15, 19, 21, 41""이...",https://n.news.naver.com/mnews/article/015/000...
...,...,...,...,...,...
61,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
62,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
63,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
64,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
65,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...

In [101]:
oid = '022'
date = '20221210'
page = '1'

url = f'https://news.naver.com/main/list.naver?mode=LPOD&mid=sec&oid={oid}&date={date}&page={page}'
bs_page = bs_object_from_url(url)

title_and_content_links = bs_page.select('dt > a')[1::2]

for title_and_content_link in tqdm(title_and_content_links) :
    titles = title_and_content_link.text.strip()
    content_url = title_and_content_link.get('href')
    content = get_contents_from_rul(content_url)

    title = row.title.replace('\'','\"')
    content = row.content.replace('\'','\"') if content != -1 else content
    
    cur.execute(f"INSERT INTO naver_news values ('{date}','{oid}','{title}','{content}','{content_url}');")
    conn.commit()

100%|██████████| 23/23 [00:05<00:00,  4.46it/s]

In [100]:
pd.read_sql('select * from naver_news ;',conn)

c:\Users\user\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,date,oid,title,content,content_url
0,20221210,015,"5년간 멈췄던 ""한빛 4호기"" 재가동","원안위 ""원전 안전성 확인""\n\n\n\n원자력안전위원회가 안전 점검 명목으로 5년...",https://n.news.naver.com/mnews/article/015/000...
1,20221210,015,"부결 하루 만에…""한전채 확대법"" 재추진하는 국회","전기료 인상 등 ""전력대란"" 우려에 여야, 부랴부랴 본회의 상정 속도여야가 9일 한...",https://n.news.naver.com/mnews/article/015/000...
2,20221210,015,"이태원 참사 유가족협의회 출범…권성동 ""세월호"" 언급 논란","사진=연합뉴스이태원 참사 희생자 유가족이 만든 협의체가 10일 공식 발족한 가운데,...",https://n.news.naver.com/mnews/article/015/000...
3,20221210,015,"오열하던 네이마르 위로한 소년, 정체 알고 보니 ""반전""",사진=AFP2022 카타르 월드컵 8강전에서 패배한 후 눈물을 쏟은 네이마르를 위로...,https://n.news.naver.com/mnews/article/015/000...
4,20221210,015,"1045회 로또 1등 ""6, 14, 15, 19, 21, 41""…당첨자 13명 19억씩","10일 제1045회 로또복권 추첨 결과 ""6, 14, 15, 19, 21, 41""이...",https://n.news.naver.com/mnews/article/015/000...
...,...,...,...,...,...
107,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
108,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
109,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
110,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...
111,20221210,022,"카타르 월드컵 8강전 취재하던 美 기자, 경기 중 돌연 사망",네덜란드-아르헨티나 8강전 모습 / 사진=AP2022 카타르 월드컵을 취재하던 미국...,https://n.news.naver.com/mnews/article/022/000...

In [103]:
news_data.to_csv('news_data.csv',index= False, encoding='utf-8-sig')

### psycopg2

설치
```cmd
pip install psycopg2
pip install psycopg2-binary #위의 설치 에러 시 이 코드 실행
```
<br>

사용법
```python
conn = psycopg2.connect(
  host='address',
  dbname='database name',
  user='user name',
  password='password',
  port=port

cur = conn.cursor()
```

CRUD
```python
cur.execute(f'INSERT INTO test (id, press_name) VALUES ({id}, {press_name});')
conn.commit() # CREATE

cur.execute('SELECT * FROM test;')
result_one = cur.fetchone() # READ
result_many = cur.fetchmany() 
result_all = cur.fetchall() 

cur.execute(f'UPDATE test SET press_name={press_name} WHERE id > 5')
conn.commit() # UPDATE

cur.execute('DELETE FROM test WHERE press_name LIKE %조선%;')
conn.commit() # DELETE
```
<br>

pandas 내의 method를 통해서도 사용 가능
```python
pd.read_sql('SELECT * FROM test', conn)
```
<br>

Closer <br>
사용 후 연결 해제 <br>
```python
cur.close()
conn.close()
```
<br>

아래와 같이 사용 가능
```python
with conn.cursor() as cur:
  cur.execute(query)

conn.close()

with psycopg2.connect():
  with conn.cursor() as cur:
    cur.execute(query)
```

### sqlalchemy

설치
```cmd
pip install sqlalchemy
```
<br>

사용법
```python
from sqlalchemy import create_engine
from sqlalchemy.types import Integer, Text, String, DateTime

db_url = f'postgres+psycopg2://{USERNAME}:{PASSWORD}@{DB_HOST}:{PORT}/{DB_NAME}'
engine = create_engine(db_url, echo=True)

test.to_sql(
  'schema',
  engine,
  if_exists='append', # replace: 덮어쓰기
  index=False,
  chunksize=5000,
  dtypes={
    'id': Integer,
    'press_name': Text
  }
)
```